// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package v1alpha1

import (
	"context"
	"fmt"

	refsv1beta1 "github.com/GoogleCloudPlatform/k8s-config-connector/apis/refs/v1beta1"
	"github.com/GoogleCloudPlatform/k8s-config-connector/pkg/k8s"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

var _ refsv1beta1.ExternalNormalizer = &MemorystoreInstanceServiceAttachmentRef{}

// MemorystoreInstanceServiceAttachmentRef defines the resource reference to the GCP identifier
// for the ServiceAttachment managed by the MemorystoreInstance pointed by the MemorystoreInstanceRef.
type MemorystoreInstanceServiceAttachmentRef struct {
	// A reference to a ServiceAttachment managed by aMemorystoreInstance resource.
	ServiceAttachmentExternal string `json:"serviceAttachmentExternal,omitempty"`

	// The name of a MemorystoreInstance resource.
	MemorystoreInstanceRef *refsv1beta1.MemorystoreInstanceRef `json:"memorystoreInstanceRef,omitempty"`

	// The index of the PSC attachment details.
	PscAttachmentDetailsIndex *int `json:"pscAttachmentDetailsIndex,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MemorystoreInstanceServiceAttachmentRef) DeepCopyInto(out *MemorystoreInstanceServiceAttachmentRef) {
	*out = *in
	if in.MemorystoreInstanceRef != nil {
		in, out := &in.MemorystoreInstanceRef, &out.MemorystoreInstanceRef
		*out = new(refsv1beta1.MemorystoreInstanceRef)
		**out = **in
	}
	if in.PscAttachmentDetailsIndex != nil {
		in, out := &in.PscAttachmentDetailsIndex, &out.PscAttachmentDetailsIndex
		*out = new(int)
		**out = **in
	}
}

func (in *MemorystoreInstanceServiceAttachmentRef) DeepCopy() *MemorystoreInstanceServiceAttachmentRef {
	if in == nil {
		return nil
	}
	out := new(MemorystoreInstanceServiceAttachmentRef)
	in.DeepCopyInto(out)
	return out
}

func (r *MemorystoreInstanceServiceAttachmentRef) NormalizedExternal(ctx context.Context, reader client.Reader, otherNamespace string) (string, error) {
	if r.ServiceAttachmentExternal != "" {
		if r.MemorystoreInstanceRef == nil || r.MemorystoreInstanceRef.Name == "" || r.PscAttachmentDetailsIndex == nil {
			return "", fmt.Errorf("must specify either serviceAttachmentExternal or (memorystoreInstanceRef.Name and pscAttachmentDetailsIndex)")
		}

		key := types.NamespacedName{
			Namespace: r.MemorystoreInstanceRef.Namespace,
			Name:      r.MemorystoreInstanceRef.Name,
		}
		if key.Namespace == "" {
			key.Namespace = otherNamespace
		}
		u := &unstructured.Unstructured{}
		u.SetGroupVersionKind(schema.GroupVersionKind{
			Group:   "memorystore.cnrm.cloud.google.com",
			Version: "v1beta1",
			Kind:    "MemorystoreInstance",
		})
		if err := reader.Get(ctx, key, u); err != nil {
			if apierrors.IsNotFound(err) {
				return "", k8s.NewReferenceNotFoundError(u.GroupVersionKind(), key)
			}
			return "", fmt.Errorf("reading referenced %s %s: %w", u.GroupVersionKind(), key, err)
		}

		// Read status.observedState.pscAttachmentDetails[MemorystoreInstanceServiceAttachmentIndex]
		// to retrieve the service attachment external.
		pscAttachmentDetails, found, err := unstructured.NestedSlice(u.Object, "status", "observedState", "pscAttachmentDetails")
		if err != nil {
			return "", fmt.Errorf("getting status.observedState.pscAttachmentDetails[]: %w", err)
		}
		if !found {
			return "", k8s.NewReferenceNotFoundError(u.GroupVersionKind(), key)
		}
		if len(pscAttachmentDetails) <= int(*r.PscAttachmentDetailsIndex) {
			return "", fmt.Errorf("pscAttachmentDetailsindex is out of range")
		}

		pscAttachmentDetail, ok := pscAttachmentDetails[*r.PscAttachmentDetailsIndex].(map[string]interface{})
		if !ok {
			return "", fmt.Errorf("failed getting status.observedState.pscAttachmentDetails[%d]", *r.PscAttachmentDetailsIndex)
		}
		serviceAttachmentExternal, ok := pscAttachmentDetail["serviceAttachment"].(string)
		if !ok {
			return "", fmt.Errorf("failed getting status.observedState.pscAttachmentDetails[%d].serviceAttachment", *r.PscAttachmentDetailsIndex)
		}
		r.ServiceAttachmentExternal = serviceAttachmentExternal
	}
	return r.ServiceAttachmentExternal, nil
}
